# Data Cleaning Exploration
## Part 1: Core Cleaning Steps
---

In [63]:
import pandas as pd
import numpy as np

In [64]:
df = pd.read_csv('data.csv')
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,NaN,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,NaN,NaN
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,NaN,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,NaN,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,NaN
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
15,103,Rohit Mehta,-5,Sales,male,NaN,2021,6.9,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [65]:
df.dtypes

employee_id            int64
name                     str
age                    int64
department               str
gender                   str
salary               float64
joining_year           int64
performance_score    float64
city                     str
dtype: object

In [66]:
df.shape

(17, 9)

In [67]:
df.isnull().any()

employee_id          False
name                 False
age                  False
department           False
gender               False
salary                True
joining_year         False
performance_score     True
city                  True
dtype: bool

In [68]:
df.isnull().sum()

employee_id          0
name                 0
age                  0
department           0
gender               0
salary               3
joining_year         0
performance_score    2
city                 2
dtype: int64

In [69]:
df['salary']

0     45000.0
1     52000.0
2         NaN
3     61000.0
4     75000.0
5     48000.0
6         NaN
7     90000.0
8     82000.0
9     43000.0
10    55000.0
11    70000.0
12    67000.0
13    49000.0
14    95000.0
15        NaN
16    90000.0
Name: salary, dtype: float64

In [70]:
df['salary'] = round(df['salary'].fillna(df['salary'].mean()))
df['salary']

0     45000.0
1     52000.0
2     65857.0
3     61000.0
4     75000.0
5     48000.0
6     65857.0
7     90000.0
8     82000.0
9     43000.0
10    55000.0
11    70000.0
12    67000.0
13    49000.0
14    95000.0
15    65857.0
16    90000.0
Name: salary, dtype: float64

In [71]:
df['performance_score']

0     8.2
1     7.5
2     6.9
3     NaN
4     9.1
5     7.8
6     8.5
7     NaN
8     7.2
9     8.9
10    6.5
11    9.3
12    7.1
13    8.0
14    9.8
15    6.9
16    8.5
Name: performance_score, dtype: float64

In [72]:
df['performance_score'] = df['performance_score'].fillna(df['performance_score'].mean())
df['performance_score'] = df['performance_score'].round(1)
df['performance_score']

0     8.2
1     7.5
2     6.9
3     8.0
4     9.1
5     7.8
6     8.5
7     8.0
8     7.2
9     8.9
10    6.5
11    9.3
12    7.1
13    8.0
14    9.8
15    6.9
16    8.5
Name: performance_score, dtype: float64

In [73]:
df['city'] = df['city'].fillna(df['city'].mode()[0])
df['city']

0        Mumbai
1         Delhi
2        Mumbai
3        Mumbai
4     Bangalore
5          Pune
6        Mumbai
7     Hyderabad
8       Chennai
9        Mumbai
10       Mumbai
11    Bangalore
12        Delhi
13         Pune
14       Mumbai
15       Mumbai
16    Hyderabad
Name: city, dtype: str

In [74]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
15,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [75]:
df = df.drop_duplicates()

In [76]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [77]:
df.shape

(16, 9)

In [78]:
Q1 = df['age'].quantile(0.25)
Q1

np.float64(28.75)

In [79]:
Q3 = df['age'].quantile(0.75)
Q3

np.float64(42.0)

In [80]:
IQR = Q3-Q1
IQR

np.float64(13.25)

In [81]:
lower_bound = Q1 - (1.5*IQR)
lower_bound

np.float64(8.875)

In [82]:
upper_bound = Q3 + (1.5*IQR)
upper_bound

np.float64(61.875)

In [83]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [84]:
age_median = round(df['age'].median())
age_median

34

In [85]:
outliers = (df['age'] < lower_bound) | (df['age'] > upper_bound)
outliers

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
16     True
Name: age, dtype: bool

In [86]:
df.loc[outliers,'age'] = age_median

In [87]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,34,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,34,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,34,IT,MALE,90000.0,2015,8.5,Hyderabad

In [88]:
df['gender'] = df['gender'].str.title()
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,34,Sales,Male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,Female,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,Female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,Male,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,34,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,Male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,Female,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,Male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,34,IT,Male,90000.0,2015,8.5,Hyderabad

In [89]:
df['gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

---
## Part 2: Advanced Cleaning Techniques
---

In [2]:
import pandas as pd
import numpy as np

# Load the messy data
df = pd.read_csv('sample_datasets/marketing_campaign_data_messy.csv')

print(f"Loaded Dataset: {df.shape[0]} rows, {df.shape[1]} columns")

Loaded Dataset: 2020 rows, 12 columns

In [3]:
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [ ]:
# HEADER CLEANING


print(df.columns.tolist())

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

print("FIX APPLIED")
print(df.columns.tolist())

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']
FIX APPLIED
['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel', 'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks', 'campaign_tag']

In [ ]:
# TYPE CONVERSION & CURRENCY CLEANING

dirty_spend_mask = df['spend'].astype(str).str.contains(r'\$')
print(df.loc[dirty_spend_mask,['campaign_id','spend']].head(3))

df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex=True)
df['spend'] = pd.to_numeric(df['spend'])

print("FIX APPLIED")
print(df.loc[dirty_spend_mask,['campaign_id','spend']].head(3))

   campaign_id     spend
0    CMP-00001   $102.82
21   CMP-00022   $2428.4
22   CMP-00023  $4726.22
FIX APPLIED
   campaign_id    spend
0    CMP-00001   102.82
21   CMP-00022  2428.40
22   CMP-00023  4726.22

In [ ]:

# DATE PARSING


print(df['start_date'].dtype)

df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce')
df['end_date'] = pd.to_datetime(df['end_date'], dayfirst=True, errors='coerce')

print("FIX APPLIED")
print(df['start_date'].dtype)

str
FIX APPLIED
datetime64[us]

C:\Users\ACER\AppData\Local\Temp\ipykernel_256\877702922.py:8: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date'] = pd.to_datetime(df['end_date'], dayfirst=True, errors='coerce')

In [9]:
df = df.loc[:, ~df.columns.duplicated()]

In [10]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM

In [ ]:
# HANDLING OUTLIERS (WINSORIZING)


Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3 - Q1
upper_limit = Q3 + (3 * IQR)

outlier_mask = df['spend'] > upper_limit
print(df.loc[outlier_mask,['campaign_id','spend']].head(3))

print("FIX APPLIED")
df.loc[outlier_mask, 'spend'] = upper_limit
print(df.loc[outlier_mask,['campaign_id','spend']].head(3))

     campaign_id      spend
789    CMP-00790  500000.00
1443   CMP-01444    8921.51
1460   CMP-01461  500000.00
FIX APPLIED
     campaign_id      spend
789    CMP-00790  8603.5375
1443   CMP-01444  8603.5375
1460   CMP-01461  8603.5375

In [15]:
df.head(50)

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag,season
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI,Summer
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA,Launch
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM,Winter
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI,BlackFriday
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA,Winter
5,CMP-00006,Q4_BlackFriday_CMP-00006,2023-10-15,2023-10-28,Instagram,83386,2643,2697.03,NaN,True,IN,BlackFriday
6,CMP-00007,Q3_Launch_CMP-00007,2023-10-07,2023-10-23,Facebook,38194,1135,1232.76,178.0,True,FA,Launch
7,CMP-00008,Q4_Launch_CMP-00008,NaT,2023-05-28,Instagram,88498,1173,865.70,127.0,True,IN,Launch
8,CMP-00009,Q4_BlackFriday_CMP-00009,2023-03-23,2023-04-01,Google Ads,45131,1179,1046.18,104.0,True,GO,BlackFriday
9,CMP-00010,Q2_Winter_CMP-00010,2023-03-21,2023-04-01,Email,61263,1153,1623.56,NaN,False,EM,Winter
10,CMP-00011,Q4_Launch_CMP-00011,NaT,2023-03-01,Instagram,17023,455,523.13,76.0,True,IN,Launch
11,CMP-00012,Q4_Launch_CMP-00012,2023-02-19,2023-02-20,Google Ads,42090,763,1267.69,109.0,False,GO,Launch
12,CMP-00013,Q2_Launch_CMP-00013,2023-05-16,2023-06-01,Google Ads,68221,2975,5292.16,567.0,False,GO,Launch
13,CMP-00014,Q1_Launch_CMP-00014,2023-10-02,2023-10-15,TikTok,65820,1116,1464.72,169.0,True,TI,Launch
14,CMP-00015,Q2_Summer_CMP-00015,2023-02-10,2023-02-16,Google Ads,1769,85,139.18,11.0,True,GO,Summer
15,CMP-00016,Q2_BlackFriday_CMP-00016,2023-11-13,2023-11-23,Email,60735,1617,1552.90,228.0,True,E-,BlackFriday
16,CMP-00017,Q1_Winter_CMP-00017,NaT,2023-10-01,Email,63955,2804,3147.37,536.0,False,EM,Winter
17,CMP-00018,Q1_BlackFriday_CMP-00018,2023-04-27,2023-05-25,Instagram,65925,2317,3635.76,389.0,False,IN,BlackFriday
18,CMP-00019,Q4_Winter_CMP-00019,2023-04-30,2023-05-18,Facebook,68969,2718,2933.59,145.0,False,FA,Winter
19,CMP-00020,Q1_Summer_CMP-00020,2023-08-21,2023-08-30,Email,6311,256,353.99,NaN,True,INVALID,Summer
20,CMP-00021,Q3_BlackFriday_CMP-00021,2023-07-09,2023-07-17,Facebook,84104,2539,1975.49,NaN,True,FA,BlackFriday
21,CMP-00022,Q2_BlackFriday_CMP-00022,2023-12-26,2024-01-02,Google Ads,54707,1735,2428.40,NaN,True,GO,BlackFriday
22,CMP-00023,Q4_Winter_CMP-00023,2023-11-08,2023-11-24,Google Ads,86305,2637,4726.22,216.0,False,GO,Winter
23,CMP-00024,Q4_Winter_CMP-00024,2023-05-06,2023-06-05,Instagram,29693,995,1793.94,179.0,False,IN,Winter
24,CMP-00025,Q2_Winter_CMP-00025,2023-11-24,2023-12-18,Email,72932,815,1293.01,157.0,False,EM,Winter
25,CMP-00026,Q1_Winter_CMP-00026,2023-06-16,2023-07-02,Google Ads,94016,2427,3928.42,207.0,False,GO,Winter
26,CMP-00027,Q1_Winter_CMP-00027,2023-04-28,2023-05-12,TikTok,26658,912,1219.24,166.0,False,TI,Winter
27,CMP-00028,Q4_Summer_CMP-00028,2023-07-25,2023-08-08,Email,85478,2898,3990.55,187.0,True,EM,Summer
28,CMP-00029,Q4_BlackFriday_CMP-00029,2023-10-18,2023-11-15,Instagram,19431,810,567.39,47.0,True,IN,BlackFriday
29,CMP-00030,Q1_Summer_CMP-00030,2023-12-02,2023-12-08,Instagram,3747,135,157.38,9.0,False,IN,Summer
30,CMP-00031,Q1_Launch_CMP-00031,2023-11-26,2023-12-12,Google Ads,60150,2988,3514.38,175.0,True,GO,Launch
31,CMP-00032,Q2_Summer_CMP-00032,2023-05-07,2023-05-29,Instagram,66725,1424,2759.35,251.0,False,IN,Summer
32,CMP-00033,Q2_BlackFriday_CMP-00033,2023-10-27,2023-10-29,Instagram,85654,2087,2393.02,122.0,False,IN,BlackFriday
33,CMP-00034,Q2_Summer_CMP-00034,2023-07-05,2023-07-17,Facebook,36773,932,1233.98,84.0,False,FA,Summer
34,CMP-00035,Q2_Summer_CMP-00035,2023-09-18,2023-09-22,Instagram,68435,1959,2546.46,128.0,True,IN,Summer
35,CMP-00036,Q1_Launch_CMP-00036,2023-02-26,2023-03-01,TikTok,57886,2514,3658.23,237.0,True,TI,Launch
36,CMP-00037,Q2_Winter_CMP-00037,NaT,2023-12-26,Instagram,67803,1317,2136.63,83.0,True,IN,Winter
37,CMP-00038,Q4_Winter_CMP-00038,2023-07-15,2023-08-07,TikTok,32551,1335,1118.15,200.0,True,TI,Winter
38,CMP-00039,Q3_Launch_CMP-00039,2023-05-09,2023-05-25,Email,12394,324,418.96,22.0,True,EM,Launch
39,CMP-00040,Q4_BlackFriday_CMP-00040,2023-01-06,2023-01-26,Email,70092,2388,4152.44,424.0,False,EM,BlackFriday
40,CMP-00041,Q4_Summer_CMP-00041,2023-10-02,2023-10-12,Email,4890,172,205.48,29.0,False,EM,Summer
41,CMP-00042,Q3_Summer_CMP-00042,2023-06-24,2023-06-29,TikTok,42606,1061,973.67,55.0,True,TI,Summer
42,CMP-00043,Q2_Summer_CMP-00043,NaT,2023-08-29,Instagram,97276,2967,4397.28,546.0,True,IN,Summer
43,CMP-00044,Q1_Winter_CMP-00044,2023-05-15,2023-06-01,Email,81038,2149,3729.91,116.0,True,E-,Winter
44,CMP-00045,Q2_Summer_CMP-00045,2023-09-17,2023-10-03,TikTok,88313,1127,670.24,96.0,False,TI,Summer
45,CMP-00046,Q4_Launch_CMP-00046,2023-06-02,2023-06-28,Instagram,11627,319,531.19,17.0,False,IN,Launch
46,CMP-00047,Q4_BlackFriday_CMP-00047,2023-04-12,2023-04-19,Google Ads,9792,136,235.62,13.0,True,GO,BlackFriday
47,CMP-00048,Q3_Winter_CMP-00048,2023-10-04,2023-10-18,Email,74969,1964,2341.65,249.0,True,EM,Winter
48,CMP-00049,Q4_Winter_CMP-00049,2023-01-01,2023-01-17,Facebook,44001,1483,2928.86,NaN,False,FA,Winter
49,CMP-00050,Q3_Summer_CMP-00050,2023-02-27,2023-02-28,Email,77552,2572,4321.12,258.0,False,INVALID,Summer

In [28]:
df = pd.read_csv('S:\Python\Python Scripts\DataCleaner\Data_Cleaning_Adv\sample_datasets\marketing_campaign_data_messy.csv')
df = pd.read_csv('Final_Data.csv')
print(df.dtypes)
print(df.isnull().sum())
print(df['channel'].unique())

campaign_id          str
campaign_name        str
start_date           str
end_date             str
channel              str
impressions      float64
clicks           float64
spend            float64
conversions      float64
active               str
campaign_tag         str
dtype: object
campaign_id      0
campaign_name    0
start_date       0
end_date         0
channel          0
impressions      0
clicks           0
spend            0
conversions      0
active           0
campaign_tag     0
dtype: int64
<StringArray>
[    'Tiktok',   'Facebook',      'Email',  'Instagram', 'Google Ads',
     'E-Mail',      'Gogle',    'Tik_Tok',    'Facebok', 'Insta_Gram']
Length: 10, dtype: str

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\ACER\AppData\Local\Temp\ipykernel_256\891022078.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('S:\Python\Python Scripts\DataCleaner\Data_Cleaning_Adv\sample_datasets\marketing_campaign_data_messy.csv')

In [29]:
pd.read_csv('S:\Python\Python Scripts\DataCleaner\Data_Cleaning_Adv\sample_datasets\marketing_campaign_data_messy.csv').head(50)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\ACER\AppData\Local\Temp\ipykernel_256\1697439573.py:1: SyntaxWarning: invalid escape sequence '\P'
  pd.read_csv('S:\Python\Python Scripts\DataCleaner\Data_Cleaning_Adv\sample_datasets\marketing_campaign_data_messy.csv').head(50)

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
5,CMP-00006,Q4_BlackFriday_CMP-00006,2023-10-15 00:00:00,2023-10-28,Instagram,83386,2643,2697.03,NaN,1,NaN,IN
6,CMP-00007,Q3_Launch_CMP-00007,2023-10-07 00:00:00,2023-10-23,Facebook,38194,1135,1232.76,178.0,Yes,NaN,FA
7,CMP-00008,Q4_Launch_CMP-00008,2023-05-23,2023-05-28,Instagram,88498,1173,865.7,127.0,1,NaN,IN
8,CMP-00009,Q4_BlackFriday_CMP-00009,2023-03-23 00:00:00,2023-04-01,Google Ads,45131,1179,1046.18,104.0,1,NaN,GO
9,CMP-00010,Q2_Winter_CMP-00010,2023-03-21 00:00:00,2023-04-01,Email,61263,1153,1623.56,NaN,0,NaN,EM
10,CMP-00011,Q4_Launch_CMP-00011,22/02/2023,2023-03-01,Instagram,17023,455,523.13,76.0,1,NaN,IN
11,CMP-00012,Q4_Launch_CMP-00012,2023-02-19 00:00:00,2023-02-20,Google Ads,42090,763,1267.69,109.0,False,NaN,GO
12,CMP-00013,Q2_Launch_CMP-00013,2023-05-16 00:00:00,2023-06-01,Google Ads,68221,2975,5292.16,567.0,No,NaN,GO
13,CMP-00014,Q1_Launch_CMP-00014,2023-10-02 00:00:00,2023-10-15,TikTok,65820,1116,1464.72,169.0,Y,NaN,TI
14,CMP-00015,Q2_Summer_CMP-00015,2023-02-10 00:00:00,2023-02-16,Google Ads,1769,85,139.18,11.0,Yes,NaN,GO
15,CMP-00016,Q2_BlackFriday_CMP-00016,2023-11-13 00:00:00,2023-11-23,E-mail,60735,1617,1552.9,228.0,Y,NaN,E-
16,CMP-00017,Q1_Winter_CMP-00017,2023-04-09,2023-10-01,Email,63955,2804,3147.37,536.0,No,NaN,EM
17,CMP-00018,Q1_BlackFriday_CMP-00018,2023-04-27 00:00:00,2023-05-25,Instagram,65925,2317,3635.76,389.0,True,NaN,IN
18,CMP-00019,Q4_Winter_CMP-00019,2023-04-30 00:00:00,2023-05-18,Facebook,68969,2718,2933.59,145.0,No,NaN,FA
19,CMP-00020,Q1_Summer_CMP-00020,2023-08-21 00:00:00,2023-08-30,Email,6311,256,353.99,NaN,Yes,NaN,INVALID
20,CMP-00021,Q3_BlackFriday_CMP-00021,2023-07-09 00:00:00,2023-07-17,Facebook,84104,2539,1975.49,NaN,Y,NaN,FA
21,CMP-00022,Q2_BlackFriday_CMP-00022,2023-12-26 00:00:00,2024-01-02,Google Ads,54707,1735,$2428.4,NaN,Y,NaN,GO
22,CMP-00023,Q4_Winter_CMP-00023,2023-11-08 00:00:00,2023-11-24,Google Ads,86305,2637,$4726.22,216.0,0,86385.0,GO
23,CMP-00024,Q4_Winter_CMP-00024,2023-05-06 00:00:00,2023-05-01,Instagram,29693,995,1793.94,179.0,0,NaN,IN
24,CMP-00025,Q2_Winter_CMP-00025,2023-11-24 00:00:00,2023-12-18,Email,72932,815,1293.01,157.0,No,NaN,EM
25,CMP-00026,Q1_Winter_CMP-00026,2023-06-16 00:00:00,2023-07-02,Google Ads,94016,2427,3928.42,207.0,No,NaN,GO
26,CMP-00027,Q1_Winter_CMP-00027,2023-04-28 00:00:00,2023-05-12,TikTok,26658,912,1219.24,166.0,True,NaN,TI
27,CMP-00028,Q4_Summer_CMP-00028,2023-07-25 00:00:00,2023-08-08,Email,85478,2898,3990.55,187.0,1,NaN,EM
28,CMP-00029,Q4_BlackFriday_CMP-00029,2023-10-18 00:00:00,2023-11-15,Instagram,19431,810,567.39,47.0,Yes,NaN,IN
29,CMP-00030,Q1_Summer_CMP-00030,2023-12-02 00:00:00,2023-12-08,Instagram,3747,135,157.38,9.0,0,NaN,IN
30,CMP-00031,Q1_Launch_CMP-00031,2023-11-26 00:00:00,2023-12-12,Google Ads,60150,2988,3514.38,175.0,Yes,NaN,GO
31,CMP-00032,Q2_Summer_CMP-00032,2023-05-07 00:00:00,2023-05-29,Instagram,66725,1424,$2759.35,251.0,True,NaN,IN
32,CMP-00033,Q2_BlackFriday_CMP-00033,2023-10-27 00:00:00,2023-10-29,Instagram,85654,2087,$2393.02,122.0,0,NaN,IN
33,CMP-00034,Q2_Summer_CMP-00034,2023-07-05 00:00:00,2023-07-17,Facebook,36773,932,1233.98,84.0,0,NaN,FA
34,CMP-00035,Q2_Summer_CMP-00035,2023-09-18 00:00:00,2023-09-22,Instagram,68435,1959,2546.46,128.0,1,NaN,IN
35,CMP-00036,Q1_Launch_CMP-00036,2023-02-26 00:00:00,2023-03-01,TikTok,57886,2514,3658.23,237.0,Yes,NaN,TI
36,CMP-00037,Q2_Winter_CMP-00037,2023-12-15,2023-12-26,Instagram,67803,1317,$2136.63,83.0,Yes,NaN,IN
37,CMP-00038,Q4_Winter_CMP-00038,2023-07-15 00:00:00,2023-08-07,TikTok,32551,1335,$1118.15,200.0,Yes,NaN,TI
38,CMP-00039,Q3_Launch_CMP-00039,2023-05-09 00:00:00,2023-05-25,Email,12394,324,418.96,22.0,1,NaN,EM
39,CMP-00040,Q4_BlackFriday_CMP-00040,2023-01-06 00:00:00,2023-01-26,Email,70092,2388,4152.44,424.0,0,NaN,EM
40,CMP-00041,Q4_Summer_CMP-00041,2023-10-02 00:00:00,2023-10-12,Email,4890,172,$205.48,29.0,True,NaN,EM
41,CMP-00042,Q3_Summer_CMP-00042,2023-06-24 00:00:00,2023-06-29,TikTok,42606,1061,973.67,55.0,Yes,NaN,TI
42,CMP-00043,Q2_Summer_CMP-00043,21/08/2023,2023-08-29,Instagram,97276,2967,4397.28,546.0,Y,NaN,IN
43,CMP-00044,Q1_Winter_CMP-00044,2023-05-15 00:00:00,2023-06-01,E-mail,81038,2149,3729.91,116.0,1,81075.0,E-
44,CMP-00045,Q2_Summer_CMP-00045,2023-09-17 00:00:00,2023-10-03,TikTok,88313,1127,670.24,96.0,False,NaN,TI
45,CMP-00046,Q4_Launch_CMP-00046,2023-06-02 00:00:00,2023-06-28,Instagram,11627,319,531.19,17.0,True,NaN,IN
46,CMP-00047,Q4_BlackFriday_CMP-00047,2023-04-12 00:00:00,2023-04-19,Google Ads,9792,136,235.62,13.0,Y,NaN,GO
47,CMP-00048,Q3_Winter_CMP-00048,2023-10-04 00:00:00,2023-10-18,Email,74969,1964,2341.65,249.0,Yes,NaN,EM
48,CMP-00049,Q4_Winter_CMP-00049,2023-01-01 00:00:00,2023-01-17,Facebook,44001,1483,2928.86,NaN,False,NaN,FA
49,CMP-00050,Q3_Summer_CMP-00050,2023-02-27 00:00:00,2023-02-28,Email,77552,2572,4321.12,258.0,True,NaN,INVALID

In [30]:
pd.read_csv('S:\Python\Python Scripts\DataCleaner\Data_Cleaning_Adv\Final_Data.csv').head(50)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\ACER\AppData\Local\Temp\ipykernel_256\3536424345.py:1: SyntaxWarning: invalid escape sequence '\P'
  pd.read_csv('S:\Python\Python Scripts\DataCleaner\Data_Cleaning_Adv\Final_Data.csv').head(50)

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,Tiktok,16795.0,197.0,102.82,20.0,Y,Ti
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860.0,30.0,24.33,1.0,0,Fa
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820.0,843.0,1323.39,51.0,No,Em
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,Tiktok,55886.0,2019.0,2180.38,135.0,True,Ti
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265.0,169.0,252.44,30.0,Yes,Fa
5,CMP-00006,Q4_BlackFriday_CMP-00006,2023-10-15,2023-10-28,Instagram,83386.0,2643.0,2697.03,142.0,1,In
6,CMP-00007,Q3_Launch_CMP-00007,2023-10-07,2023-10-23,Facebook,38194.0,1135.0,1232.76,178.0,Yes,Fa
7,CMP-00008,Q4_Launch_CMP-00008,2023-05-23,2023-05-28,Instagram,88498.0,1173.0,865.70,127.0,1,In
8,CMP-00009,Q4_BlackFriday_CMP-00009,2023-03-23,2023-04-01,Google Ads,45131.0,1179.0,1046.18,104.0,1,Go
9,CMP-00010,Q2_Winter_CMP-00010,2023-03-21,2023-04-01,Email,61263.0,1153.0,1623.56,142.0,0,Em
10,CMP-00011,Q4_Launch_CMP-00011,2023-02-22,2023-03-01,Instagram,17023.0,455.0,523.13,76.0,1,In
11,CMP-00012,Q4_Launch_CMP-00012,2023-02-19,2023-02-20,Google Ads,42090.0,763.0,1267.69,109.0,False,Go
12,CMP-00013,Q2_Launch_CMP-00013,2023-05-16,2023-06-01,Google Ads,68221.0,2975.0,5292.16,488.5,No,Go
13,CMP-00014,Q1_Launch_CMP-00014,2023-10-02,2023-10-15,Tiktok,65820.0,1116.0,1464.72,169.0,Y,Ti
14,CMP-00015,Q2_Summer_CMP-00015,2023-02-10,2023-02-16,Google Ads,1769.0,85.0,139.18,11.0,Yes,Go
15,CMP-00016,Q2_BlackFriday_CMP-00016,2023-11-13,2023-11-23,E-Mail,60735.0,1617.0,1552.90,228.0,Y,E-
16,CMP-00017,Q1_Winter_CMP-00017,2023-04-09,2023-10-01,Email,63955.0,2804.0,3147.37,488.5,No,Em
17,CMP-00018,Q1_BlackFriday_CMP-00018,2023-04-27,2023-05-25,Instagram,65925.0,2317.0,3635.76,389.0,True,In
18,CMP-00019,Q4_Winter_CMP-00019,2023-04-30,2023-05-18,Facebook,68969.0,2718.0,2933.59,145.0,No,Fa
19,CMP-00020,Q1_Summer_CMP-00020,2023-08-21,2023-08-30,Email,6311.0,256.0,353.99,142.0,Yes,Invalid
20,CMP-00021,Q3_BlackFriday_CMP-00021,2023-07-09,2023-07-17,Facebook,84104.0,2539.0,1975.49,142.0,Y,Fa
21,CMP-00022,Q2_BlackFriday_CMP-00022,2023-12-26,2024-01-02,Google Ads,54707.0,1735.0,2428.40,142.0,Y,Go
22,CMP-00023,Q4_Winter_CMP-00023,2023-11-08,2023-11-24,Google Ads,86305.0,2637.0,4726.22,216.0,0,Go
23,CMP-00024,Q4_Winter_CMP-00024,2023-05-06,2023-05-01,Instagram,29693.0,995.0,1793.94,179.0,0,In
24,CMP-00025,Q2_Winter_CMP-00025,2023-11-24,2023-12-18,Email,72932.0,815.0,1293.01,157.0,No,Em
25,CMP-00026,Q1_Winter_CMP-00026,2023-06-16,2023-07-02,Google Ads,94016.0,2427.0,3928.42,207.0,No,Go
26,CMP-00027,Q1_Winter_CMP-00027,2023-04-28,2023-05-12,Tiktok,26658.0,912.0,1219.24,166.0,True,Ti
27,CMP-00028,Q4_Summer_CMP-00028,2023-07-25,2023-08-08,Email,85478.0,2898.0,3990.55,187.0,1,Em
28,CMP-00029,Q4_BlackFriday_CMP-00029,2023-10-18,2023-11-15,Instagram,19431.0,810.0,567.39,47.0,Yes,In
29,CMP-00030,Q1_Summer_CMP-00030,2023-12-02,2023-12-08,Instagram,3747.0,135.0,157.38,9.0,0,In
30,CMP-00031,Q1_Launch_CMP-00031,2023-11-26,2023-12-12,Google Ads,60150.0,2988.0,3514.38,175.0,Yes,Go
31,CMP-00032,Q2_Summer_CMP-00032,2023-05-07,2023-05-29,Instagram,66725.0,1424.0,2759.35,251.0,True,In
32,CMP-00033,Q2_BlackFriday_CMP-00033,2023-10-27,2023-10-29,Instagram,85654.0,2087.0,2393.02,122.0,0,In
33,CMP-00034,Q2_Summer_CMP-00034,2023-07-05,2023-07-17,Facebook,36773.0,932.0,1233.98,84.0,0,Fa
34,CMP-00035,Q2_Summer_CMP-00035,2023-09-18,2023-09-22,Instagram,68435.0,1959.0,2546.46,128.0,1,In
35,CMP-00036,Q1_Launch_CMP-00036,2023-02-26,2023-03-01,Tiktok,57886.0,2514.0,3658.23,237.0,Yes,Ti
36,CMP-00037,Q2_Winter_CMP-00037,2023-12-15,2023-12-26,Instagram,67803.0,1317.0,2136.63,83.0,Yes,In
37,CMP-00038,Q4_Winter_CMP-00038,2023-07-15,2023-08-07,Tiktok,32551.0,1335.0,1118.15,200.0,Yes,Ti
38,CMP-00039,Q3_Launch_CMP-00039,2023-05-09,2023-05-25,Email,12394.0,324.0,418.96,22.0,1,Em
39,CMP-00040,Q4_BlackFriday_CMP-00040,2023-01-06,2023-01-26,Email,70092.0,2388.0,4152.44,424.0,0,Em
40,CMP-00041,Q4_Summer_CMP-00041,2023-10-02,2023-10-12,Email,4890.0,172.0,205.48,29.0,True,Em
41,CMP-00042,Q3_Summer_CMP-00042,2023-06-24,2023-06-29,Tiktok,42606.0,1061.0,973.67,55.0,Yes,Ti
42,CMP-00043,Q2_Summer_CMP-00043,2023-08-21,2023-08-29,Instagram,97276.0,2967.0,4397.28,488.5,Y,In
43,CMP-00044,Q1_Winter_CMP-00044,2023-05-15,2023-06-01,E-Mail,81038.0,2149.0,3729.91,116.0,1,E-
44,CMP-00045,Q2_Summer_CMP-00045,2023-09-17,2023-10-03,Tiktok,88313.0,1127.0,670.24,96.0,False,Ti
45,CMP-00046,Q4_Launch_CMP-00046,2023-06-02,2023-06-28,Instagram,11627.0,319.0,531.19,17.0,True,In
46,CMP-00047,Q4_BlackFriday_CMP-00047,2023-04-12,2023-04-19,Google Ads,9792.0,136.0,235.62,13.0,Y,Go
47,CMP-00048,Q3_Winter_CMP-00048,2023-10-04,2023-10-18,Email,74969.0,1964.0,2341.65,249.0,Yes,Em
48,CMP-00049,Q4_Winter_CMP-00049,2023-01-01,2023-01-17,Facebook,44001.0,1483.0,2928.86,142.0,False,Fa
49,CMP-00050,Q3_Summer_CMP-00050,2023-02-27,2023-02-28,Email,77552.0,2572.0,4321.12,258.0,True,Invalid