In [63]:
import pandas as pd
import numpy as np

In [64]:
df = pd.read_csv('data.csv')
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,NaN,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,NaN,NaN
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,NaN,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,NaN,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,NaN
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
15,103,Rohit Mehta,-5,Sales,male,NaN,2021,6.9,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [65]:
df.dtypes

employee_id            int64
name                     str
age                    int64
department               str
gender                   str
salary               float64
joining_year           int64
performance_score    float64
city                     str
dtype: object

In [66]:
df.shape

(17, 9)

In [67]:
df.isnull().any()

employee_id          False
name                 False
age                  False
department           False
gender               False
salary                True
joining_year         False
performance_score     True
city                  True
dtype: bool

In [68]:
df.isnull().sum()

employee_id          0
name                 0
age                  0
department           0
gender               0
salary               3
joining_year         0
performance_score    2
city                 2
dtype: int64

In [69]:
df['salary']

0     45000.0
1     52000.0
2         NaN
3     61000.0
4     75000.0
5     48000.0
6         NaN
7     90000.0
8     82000.0
9     43000.0
10    55000.0
11    70000.0
12    67000.0
13    49000.0
14    95000.0
15        NaN
16    90000.0
Name: salary, dtype: float64

In [70]:
df['salary'] = round(df['salary'].fillna(df['salary'].mean()))
df['salary']

0     45000.0
1     52000.0
2     65857.0
3     61000.0
4     75000.0
5     48000.0
6     65857.0
7     90000.0
8     82000.0
9     43000.0
10    55000.0
11    70000.0
12    67000.0
13    49000.0
14    95000.0
15    65857.0
16    90000.0
Name: salary, dtype: float64

In [71]:
df['performance_score']

0     8.2
1     7.5
2     6.9
3     NaN
4     9.1
5     7.8
6     8.5
7     NaN
8     7.2
9     8.9
10    6.5
11    9.3
12    7.1
13    8.0
14    9.8
15    6.9
16    8.5
Name: performance_score, dtype: float64

In [72]:
df['performance_score'] = df['performance_score'].fillna(df['performance_score'].mean())
df['performance_score'] = df['performance_score'].round(1)
df['performance_score']

0     8.2
1     7.5
2     6.9
3     8.0
4     9.1
5     7.8
6     8.5
7     8.0
8     7.2
9     8.9
10    6.5
11    9.3
12    7.1
13    8.0
14    9.8
15    6.9
16    8.5
Name: performance_score, dtype: float64

In [73]:
df['city'] = df['city'].fillna(df['city'].mode()[0])
df['city']

0        Mumbai
1         Delhi
2        Mumbai
3        Mumbai
4     Bangalore
5          Pune
6        Mumbai
7     Hyderabad
8       Chennai
9        Mumbai
10       Mumbai
11    Bangalore
12        Delhi
13         Pune
14       Mumbai
15       Mumbai
16    Hyderabad
Name: city, dtype: str

In [74]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
15,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [75]:
df = df.drop_duplicates()

In [76]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [77]:
df.shape

(16, 9)

In [78]:
Q1 = df['age'].quantile(0.25)
Q1

np.float64(28.75)

In [79]:
Q3 = df['age'].quantile(0.75)
Q3

np.float64(42.0)

In [80]:
IQR = Q3-Q1
IQR

np.float64(13.25)

In [81]:
lower_bound = Q1 - (1.5*IQR)
lower_bound

np.float64(8.875)

In [82]:
upper_bound = Q3 + (1.5*IQR)
upper_bound

np.float64(61.875)

In [83]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,-5,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,999,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,999,IT,MALE,90000.0,2015,8.5,Hyderabad

In [84]:
age_median = round(df['age'].median())
age_median

34

In [85]:
outliers = (df['age'] < lower_bound) | (df['age'] > upper_bound)
outliers

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
16     True
Name: age, dtype: bool

In [86]:
df.loc[outliers,'age'] = age_median

In [87]:
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,34,Sales,male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,FEMALE,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,MALE,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,34,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,FEMALE,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,34,IT,MALE,90000.0,2015,8.5,Hyderabad

In [88]:
df['gender'] = df['gender'].str.title()
df

,employee_id,name,age,department,gender,salary,joining_year,performance_score,city
0,101,Amit Sharma,28,Sales,Male,45000.0,2019,8.2,Mumbai
1,102,Priya Patel,34,HR,Female,52000.0,2017,7.5,Delhi
2,103,Rohit Mehta,34,Sales,Male,65857.0,2021,6.9,Mumbai
3,104,Sneha Joshi,29,IT,Female,61000.0,2020,8.0,Mumbai
4,105,Karan Desai,45,Finance,Male,75000.0,2016,9.1,Bangalore
5,106,Neha Kulkarni,31,HR,Female,48000.0,2018,7.8,Pune
6,107,Vikram Singh,27,Sales,Male,65857.0,2022,8.5,Mumbai
7,108,Ananya Rao,34,IT,Female,90000.0,2015,8.0,Hyderabad
8,109,Suresh Nair,38,Finance,Male,82000.0,2019,7.2,Chennai
9,110,Pooja Iyer,26,Sales,Female,43000.0,2023,8.9,Mumbai
10,111,Arjun Gupta,33,HR,Male,55000.0,2020,6.5,Mumbai
11,112,Divya Shah,41,IT,Female,70000.0,2018,9.3,Bangalore
12,113,Manish Tiwari,29,Finance,Male,67000.0,2017,7.1,Delhi
13,114,Riya Verma,35,Sales,Female,49000.0,2021,8.0,Pune
14,115,Sanjay Kapoor,52,HR,Male,95000.0,2014,9.8,Mumbai
16,107,Vikram Singh,34,IT,Male,90000.0,2015,8.5,Hyderabad

In [89]:
df['gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str